Algoritmo "impar ou par"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/08/2022
Var
// Seção de Declarações das variáveis 
num : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("escreva um numero")
leia (num)

se (num mod 2 = 0) entao
escreval ("numero ,",num,",é par")

senao
escreval ("numero,",num,", é impar")

fimse



Fimalgoritmo