Algoritmo "semnome"
// Escreva um algoritmo para ler um valor (do teclado) e escrever (na tela) o seu antecessor.
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2022
Var
// Seção de Declarações das variáveis 
num, numante : Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("escreva um numero")
leia (num)

numante := num - 1

Escreval("seu numero é ",numante)

Fimalgoritmo